"""
orchestrator/toolchain.py
==========================
Guess how to test a component, from the build files it already has.

Why this exists
---------------
`manifest.py` made any language expressible. It did not make any language
*discoverable*: a component with no `interlock.toml` silently falls back to
`python -m pytest .`, which on a Go or Java service exits 5 ("no tests
collected") and is recorded as `tests_could_not_run`. The verdict is correct —
nothing was proven — but the reason points at Interlock rather than at the
missing manifest, and on a polyglot repository that is every component at once.

Writing those manifests by hand means knowing, per component, what Interlock
expects. The information is already sitting in the repository: `go.mod` means
`go test ./...`, `package.json` names its own test script, a `pom.xml` means
Maven. This reads those markers so `interlock manifest` can propose a manifest
you review, rather than leaving you to write one blind.

What this is not
----------------
**A guarantee.** This is a starting point for a human, never an input to the
gate. Detection has no bearing on any verdict: nothing here is consulted during
a run, and a component's behaviour is decided entirely by the `interlock.toml`
that is actually on disk. A guessed command that does not work fails loudly the
first time it runs, which is the correct place to find out — as opposed to a
silently wrong default, which is the situation this replaces.

Every result carries `confidence`:

    "declared"  a runner config names the test command  (package.json scripts.test)
    "marker"    a build file identifies the toolchain   (go.mod -> go test ./...)
    "guess"     only source extensions were recognised; no runner was found
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# Source extensions to language. Deliberately wider than the discovery
# scanners' map: this only has to name a toolchain, not parse the file.
_EXT_TO_LANG: dict[str, str] = {
    ".py": "python",
    ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".ts": "typescript", ".tsx": "typescript", ".mts": "typescript", ".cts": "typescript",
    ".java": "java",
    ".kt": "kotlin", ".kts": "kotlin",
    ".scala": "scala",
    ".cs": "csharp",
    ".go": "go",
    ".rb": "ruby",
    ".php": "php",
    ".rs": "rust",
    ".c": "c", ".h": "c",
    ".cpp": "cpp", ".hpp": "cpp", ".cc": "cpp",
    ".swift": "swift",
    ".ex": "elixir", ".exs": "elixir",
    ".sh": "shell",
    # A schema-only component is a real component - it is how services couple
    # through a shared database. Reporting it as "unknown" hides that.
    ".sql": "sql",
}

_SKIP_DIRS = {
    "node_modules", ".git", ".hg", ".svn", ".venv", "venv", "__pycache__",
    ".tox", ".mypy_cache", ".pytest_cache", "dist", "build", "out", "target",
    "vendor", "coverage", ".next", ".nuxt", ".gradle", ".idea", ".vs",
    "bin", "obj",
}


@dataclass
class Detection:
    """What one component looks like, and how it would probably be tested."""

    language: str = "unknown"
    test_command: str | None = None
    confidence: str = "guess"
    evidence: str = ""
    """The file this was read from, so a wrong guess is traceable."""

    notes: list[str] = field(default_factory=list)
    languages_seen: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "language": self.language,
            "test_command": self.test_command,
            "confidence": self.confidence,
            "evidence": self.evidence,
            "notes": list(self.notes),
            "languages_seen": list(self.languages_seen),
        }

    def to_toml(self) -> str:
        """The `interlock.toml` this detection implies."""
        lines = [
            "# Generated by `interlock manifest --write`.",
            f"# Detected from {self.evidence or 'source files'}"
            f" (confidence: {self.confidence}).",
            "# VERIFY the command below actually runs this component's tests.",
            "",
            "[component]",
            f'language = "{self.language}"',
        ]
        if self.test_command:
            lines.append(f'test_command = "{self.test_command}"')
        else:
            lines.append("# No test runner found. Fill this in:")
            lines.append('# test_command = "..."')
        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Marker files, most specific first
# ---------------------------------------------------------------------------

def _npm(directory: Path) -> Detection | None:
    """
    Node. The one ecosystem that states its own test command.

    `npm test` runs whatever `scripts.test` declares, so the indirection is
    left in place rather than inlining the script - the package is free to
    change it without invalidating the manifest.
    """
    package = directory / "package.json"
    if not package.is_file():
        return None
    language = "typescript" if _has_ext(directory, {".ts", ".tsx"}) else "javascript"
    try:
        data = json.loads(package.read_text(encoding="utf-8", errors="replace"))
        script = (data.get("scripts") or {}).get("test")
    except (json.JSONDecodeError, OSError):
        script = None

    if isinstance(script, str) and script.strip():
        placeholder = "no test specified" in script
        return Detection(
            language=language,
            test_command=None if placeholder else "npm test",
            confidence="marker" if placeholder else "declared",
            evidence="package.json",
            notes=(
                ['package.json declares no real test script ("' + script.strip() + '")']
                if placeholder else [f"package.json scripts.test = {script.strip()!r}"]
            ),
        )
    return Detection(
        language=language, test_command=None, confidence="marker",
        evidence="package.json",
        notes=["package.json has no scripts.test - add one, or set test_command"],
    )


def _gradle(directory: Path) -> Detection | None:
    for name in ("build.gradle", "build.gradle.kts", "settings.gradle"):
        if (directory / name).is_file():
            wrapper = (directory / "gradlew").is_file()
            language = "kotlin" if name.endswith(".kts") else "java"
            return Detection(
                language=language,
                test_command="./gradlew test" if wrapper else "gradle test",
                confidence="marker",
                evidence=name,
                notes=[] if wrapper else ["no gradlew wrapper - gradle must be on PATH"],
            )
    return None


_MAKE_TEST = re.compile(r"^test\s*:", re.MULTILINE)


def _make(directory: Path) -> Detection | None:
    """A Makefile counts only when it actually declares a `test` target."""
    for name in ("Makefile", "makefile", "GNUmakefile"):
        path = directory / name
        if not path.is_file():
            continue
        try:
            if _MAKE_TEST.search(path.read_text(encoding="utf-8", errors="replace")):
                return Detection(
                    language=_dominant_language(directory) or "unknown",
                    test_command="make test",
                    confidence="marker",
                    evidence=f"{name} (test: target)",
                )
        except OSError:
            pass
    return None


def _script(directory: Path) -> Detection | None:
    for name in ("run_tests.sh", "test.sh", "scripts/test.sh"):
        if (directory / name).is_file():
            # The shell script is the test *runner*, not the language. A C
            # library tested by `sh run_tests.sh` is still C, and labelling it
            # "shell" would be actively misleading in the manifest.
            return Detection(
                language=_dominant_language(directory, ignore={"shell"}) or "shell",
                test_command=f"sh {name}",
                confidence="marker",
                evidence=name,
            )
    return None


def _simple(marker: str, language: str, command: str, evidence: str | None = None):
    def detect(directory: Path) -> Detection | None:
        if marker.startswith("*"):
            match = next(directory.glob(marker), None)
            if match is None:
                return None
            found = match.name
        elif (directory / marker).is_file():
            found = marker
        else:
            return None
        return Detection(
            language=language, test_command=command,
            confidence="marker", evidence=evidence or found,
        )

    return detect


# Order matters: a Go service with a Makefile is still a Go service, but a
# repository whose only marker is a Makefile has nothing better to go on.
_DETECTORS = (
    _simple("go.mod", "go", "go test ./..."),
    _simple("Cargo.toml", "rust", "cargo test"),
    _simple("pom.xml", "java", "mvn -B test"),
    _gradle,
    _npm,
    _simple("composer.json", "php", "composer test"),
    _simple("Gemfile", "ruby", "bundle exec rake test"),
    _simple("*.csproj", "csharp", "dotnet test"),
    _simple("*.sln", "csharp", "dotnet test"),
    _simple("pyproject.toml", "python", "python -m pytest ."),
    _simple("setup.py", "python", "python -m pytest ."),
    _simple("tox.ini", "python", "python -m pytest ."),
    _simple("CMakeLists.txt", "c", "ctest"),
    _script,
    _make,
)


# ---------------------------------------------------------------------------
# Source inspection
# ---------------------------------------------------------------------------

def _iter_source(directory: Path, budget: int = 2000):
    """Bounded walk. Detection must never cost more than the analysis it saves."""
    stack, seen = [directory], 0
    while stack and seen < budget:
        try:
            entries = list(stack.pop().iterdir())
        except OSError:
            continue
        for entry in entries:
            seen += 1
            if seen >= budget:
                return
            if entry.is_dir():
                if entry.name not in _SKIP_DIRS and not entry.name.startswith("."):
                    stack.append(entry)
            else:
                yield entry


def _language_counts(directory: Path) -> dict[str, int]:
    counts: dict[str, int] = {}
    for path in _iter_source(directory):
        language = _EXT_TO_LANG.get(path.suffix)
        if language:
            counts[language] = counts.get(language, 0) + 1
    return counts


def _dominant_language(directory: Path, ignore: set[str] | None = None) -> str | None:
    counts = _language_counts(directory)
    for name in ignore or ():
        counts.pop(name, None)
    if not counts:
        return None
    return max(counts, key=lambda k: (counts[k], k))


def _has_ext(directory: Path, suffixes: set[str]) -> bool:
    return any(p.suffix in suffixes for p in _iter_source(directory, budget=400))


def _looks_like_pytest(directory: Path) -> bool:
    if (directory / "conftest.py").is_file():
        return True
    return any(
        p.name.startswith("test_") or p.name.endswith("_test.py")
        for p in _iter_source(directory, budget=800)
        if p.suffix == ".py"
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def detect(component_dir: str | Path) -> Detection:
    """
    Best guess at how *component_dir* is built and tested.

    Never raises: an unreadable component returns a `guess` with no command,
    which reads as "you must fill this in" rather than taking the whole run
    down over one directory.
    """
    directory = Path(component_dir)
    if not directory.is_dir():
        return Detection(notes=[f"{directory} is not a directory"])

    counts = _language_counts(directory)
    seen = sorted(counts, key=lambda k: (-counts[k], k))

    for detector in _DETECTORS:
        try:
            found = detector(directory)
        except OSError:
            found = None
        if found is not None:
            found.languages_seen = seen
            _add_polyglot_note(found, counts)
            return found

    # No marker at all. Python is the only language Interlock can still test
    # without one, because the built-in default *is* pytest.
    if counts.get("python") and _looks_like_pytest(directory):
        found = Detection(
            language="python", test_command=None, confidence="marker",
            evidence="test_*.py / conftest.py",
            notes=["pytest layout - Interlock's built-in default already works, "
                   "so no manifest is required"],
        )
    else:
        dominant = _dominant_language(directory)
        found = Detection(
            language=dominant or "unknown", test_command=None, confidence="guess",
            evidence="source file extensions" if dominant else "",
            notes=(
                [f"no build file or test script found; {dominant} sources present"]
                if dominant else
                ["no recognisable source or build files"]
            ),
        )
    found.languages_seen = seen
    _add_polyglot_note(found, counts)
    return found


def _add_polyglot_note(found: Detection, counts: dict[str, int]) -> None:
    """
    Flag a component that is more than one language.

    Interlock tests a component with a single command, so a directory holding
    both a Go service and a React front end has to either declare a command
    that covers both or be split into two components. Saying so here is much
    cheaper than discovering it when half the suite silently never runs.
    """
    others = [lang for lang in counts if lang != found.language]
    if len(counts) > 1 and others:
        found.notes.append(
            "also contains " + ", ".join(sorted(others))
            + " - one test_command must cover everything you need proven, "
              "or split this into separate components"
        )


def needs_manifest(found: Detection) -> bool:
    """
    True when running Interlock without a manifest would not test this.

    Python components that already look like pytest projects are the exception:
    the built-in default is pytest, so a manifest would restate it.
    """
    if found.language == "python" and found.test_command in (None, "python -m pytest ."):
        return False
    return True
