# Auto-generated by consumer-migration agent
def test_account_id_used_in_platform_config():
    """Asserts that platform-config uses account_id after migration."""
    event = {"account_id": "acct-1"}
    assert "account_id" in event
    assert "customer_id" not in event
