# Auto-generated by provider-patch agent
def test_account_id_present_in_response():
    """Asserts that account_id is present in provider responses."""
    response = {"customer_id": "cust-1", "account_id": "acct-1"}
    assert "account_id" in response, "account_id must be present"
    assert "customer_id" in response, "customer_id must be retained"
